name: Build Manylinux Wheels

on:
  workflow_dispatch:
    inputs:
      os:
        description: OS
        required: true
        default: ubuntu-20.04
      manylinux:
        description: Manylinux
        required: true
        default: manylinux2014
      archs:
        description: CIBW_ARCHS
        required: true
        default: auto

jobs:
  build_wheels:
    name: Build ${{ github.event.inputs.os }} ${{ github.event.inputs.manylinux }} ${{ github.event.inputs.archs }}
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -Ur requirements-dev.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-*"
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ github.event.inputs.manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ github.event.inputs.manylinux }}
          CIBW_ARCHS: ${{ github.event.inputs.archs }}
          CIBW_BEFORE_BUILD: |
            curl -sSf -o /tmp/rustup-init.sh https://sh.rustup.rs
            sh /tmp/rustup-init.sh -y
          CIBW_ENVIRONMENT: PATH=$HOME/.cargo/bin:$PATH
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y freetype-devel || true
            yum install -y libxkbcommon-devel || true

            apt-get update || true
            apt install -y libfreetype-dev || true
            apt install -y libfreetype6-dev || true
            apt install -y libxkbcommon-dev || true
            apt install -y libxkbcommon-x11-dev || true

            apk update || true
            apk add freetype-dev || true
            apk add libxkbcommon-dev || true

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "${{ github.event.inputs.os }}-${{ github.event.inputs.manylinux }}"
          path: ./wheelhouse/*.whl
