name: Build Manylinux Wheels

on:
  workflow_dispatch:
    inputs:
      os:
        description: OS
        required: true
        default: ubuntu-20.04
      python:
        description: Python
        required: true
        default: "3.9"
      manylinux:
        description: Manylinux
        required: true
        default: manylinux2014
      archs:
        description: CIBW_ARCHS
        required: true
        default: auto

jobs:
  build_wheels:
    name: Build compat:${{ github.event.inputs.manylinux }}, python:${{ github.event.inputs.python }}, os:${{ github.event.inputs.os }}
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ github.event.inputs.python }}

      - name: install libs
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -q update
          sudo apt-get -q install -y rustc cargo libxkbcommon-dev libfreetype-dev

      - name: Install requirements
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -Ur requirements-dev.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* pp27-* pp30-* pp31-* pp32-* pp33-* pp34-* pp35-*"
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ github.event.inputs.manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ github.event.inputs.manylinux }}
          CIBW_ARCHS: ${{ github.event.inputs.archs }}
          CIBW_BEFORE_BUILD: |
            curl --proto '=https' --tlsv1.2 -sSf -o /tmp/rustup-init.sh https://sh.rustup.rs
            sh /tmp/rustup-init.sh -y
          CIBW_ENVIRONMENT: PATH=$HOME/.cargo/bin:$PATH
          CIBW_BEFORE_ALL_LINUX: yum install -y freetype-devel libxkbcommon-devel

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wheelhouse
          path: ./wheelhouse/*.whl
